name: flutter_project_structure
description: A package to showcase project structure and add path comments to Flutter/Dart files.
version: 1.0.0
homepage: https://github.com/yourusername/flutter_project_structure
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.7.0
  path: ^1.9.0
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  flutter_project_structure: flutter_project_structure
