name: flutter_project_structure
description: A package to showcase project structure and add path comments to Dart files.
version: 1.0.3
homepage: https://github.com/msi-shamim/flutter_project_structure
license: MIT

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.1.0
  path: ^1.9.1
  args: ^2.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14

executables:
  flutter_project_structure: flutter_project_structure
